Repository untoc-camp/comboong-note, pull requests merged in 2024-05, with the labels that each got.

#17 chore: 깃허브 연습
  README.md
Labels: chore

#19 chore: 깃허브연습2
  README.md
Labels: chore

#21 refactor: 1차 리팩토링
  .eslintrc.json
  assets/img/.DS_Store
  assets/img/drop_down.png
  assets/img/iconImg.png
  assets/modal/modal.html
  assets/modal/modal.js
  assets/popup/popup.css
  assets/popup/popup.html
  assets/popup/popup.js
  manifest.json
  package.json
  scripts/crawling.js
  scripts/notification.js
  scripts/storage.js
  service-worker.js
Labels: refactoring

#24 feat: 설정창 학과선택 추가
  assets/popup/popup.css
  assets/popup/popup.html
  assets/popup/popup.js
  package-lock.json
Labels: feature

#26 refactor: 스토리지 리팩터링
  assets/popup/popup.html
  assets/popup/popup.js
  manifest.json
  scripts/storage.js
Labels: refactoring

#29 feat: 설정 초기 데이터 지정
  scripts/setting.js
  service-worker.js
Labels: feature

#31 feat: 설정값 스토리지에 읽고 쓰기
  .DS_Store
  assets/popup/popup.html
  assets/popup/popup.js
  scripts/notification.js
  scripts/storage.js
Labels: feature

#33 feat: 설정기능 연결
  assets/popup/popup.js
  scripts/notification.js
  service-worker.js
Labels: feature

#37 chore: 공지 데이터 분할
  assets/popup/popup.js
  service-worker.js
Labels: chore

#40 refactor: 코드 리팩터링
  assets/popup/popup.js
Labels: refactoring

#46 fix: 팝업 수정
  assets/popup/popup.js
  service-worker.js
Labels: fix

#48 refactoring: 알람 수정
  assets/popup/popup.js
  scripts/notification.js
Labels: refactoring

#50 feat: 팝업창 하이퍼링크 추가 및 기타
  assets/popup/popup.css
  assets/popup/popup.html
  assets/popup/popup.js
Labels: feature

#52 refactor: 크롤링 데이터 전처리 리팩터링
  assets/popup/popup.js
  scripts/notification.js
  scripts/preprocess.js
  service-worker.js
Labels: refactoring

#54 fix: 크롤링 중복 실행 해결
  assets/popup/popup.js
  scripts/notification.js
  service-worker.js
Labels: fix

#56 feat: 네트워크_예외처리
  scripts/notification.js
Labels: feature

#60 feat: D-Day 설정
  scripts/notification.js
  service-worker.js
Labels: feature

#62 공지중복알림 해결
  assets/popup/popup.css
  assets/popup/popup.html
  assets/popup/popup.js
  scripts/notification.js
  scripts/storage.js
  service-worker.js
Labels: fix

#64 design: 아이콘 추가
  assets/img/iconImg-128.png
  assets/img/iconImg-16.png
  assets/img/iconImg-32.png
  assets/img/iconImg-48.png
  manifest.json
Labels: design

#66 chore: 전공 선택창 정컴 고정
  assets/popup/popup.html
Labels: chore

#68 chore: 불필요한 권한 삭제
  manifest.json
Labels: chore
